package common.plugin.authority.dmo;

import java.util.Date;

public class InterfacePermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_interface_permission.id
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_interface_permission.server_code
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    private String serverCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_interface_permission.server_name
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    private String serverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_interface_permission.request_method
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    private String requestMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_interface_permission.zuul_prefix
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    private String zuulPrefix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_interface_permission.request_uri
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    private String requestUri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_interface_permission.create_time
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_interface_permission.update_time
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_interface_permission.create_user_code
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    private String createUserCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_interface_permission.update_user_code
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    private String updateUserCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_interface_permission.delete_flag
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    private Integer deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_interface_permission.id
     *
     * @return the value of t_interface_permission.id
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_interface_permission.id
     *
     * @param id the value for t_interface_permission.id
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_interface_permission.server_code
     *
     * @return the value of t_interface_permission.server_code
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    public String getServerCode() {
        return serverCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_interface_permission.server_code
     *
     * @param serverCode the value for t_interface_permission.server_code
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    public void setServerCode(String serverCode) {
        this.serverCode = serverCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_interface_permission.server_name
     *
     * @return the value of t_interface_permission.server_name
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    public String getServerName() {
        return serverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_interface_permission.server_name
     *
     * @param serverName the value for t_interface_permission.server_name
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    public void setServerName(String serverName) {
        this.serverName = serverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_interface_permission.request_method
     *
     * @return the value of t_interface_permission.request_method
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    public String getRequestMethod() {
        return requestMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_interface_permission.request_method
     *
     * @param requestMethod the value for t_interface_permission.request_method
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    public void setRequestMethod(String requestMethod) {
        this.requestMethod = requestMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_interface_permission.zuul_prefix
     *
     * @return the value of t_interface_permission.zuul_prefix
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    public String getZuulPrefix() {
        return zuulPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_interface_permission.zuul_prefix
     *
     * @param zuulPrefix the value for t_interface_permission.zuul_prefix
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    public void setZuulPrefix(String zuulPrefix) {
        this.zuulPrefix = zuulPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_interface_permission.request_uri
     *
     * @return the value of t_interface_permission.request_uri
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    public String getRequestUri() {
        return requestUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_interface_permission.request_uri
     *
     * @param requestUri the value for t_interface_permission.request_uri
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    public void setRequestUri(String requestUri) {
        this.requestUri = requestUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_interface_permission.create_time
     *
     * @return the value of t_interface_permission.create_time
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_interface_permission.create_time
     *
     * @param createTime the value for t_interface_permission.create_time
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_interface_permission.update_time
     *
     * @return the value of t_interface_permission.update_time
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_interface_permission.update_time
     *
     * @param updateTime the value for t_interface_permission.update_time
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_interface_permission.create_user_code
     *
     * @return the value of t_interface_permission.create_user_code
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    public String getCreateUserCode() {
        return createUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_interface_permission.create_user_code
     *
     * @param createUserCode the value for t_interface_permission.create_user_code
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    public void setCreateUserCode(String createUserCode) {
        this.createUserCode = createUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_interface_permission.update_user_code
     *
     * @return the value of t_interface_permission.update_user_code
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    public String getUpdateUserCode() {
        return updateUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_interface_permission.update_user_code
     *
     * @param updateUserCode the value for t_interface_permission.update_user_code
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    public void setUpdateUserCode(String updateUserCode) {
        this.updateUserCode = updateUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_interface_permission.delete_flag
     *
     * @return the value of t_interface_permission.delete_flag
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_interface_permission.delete_flag
     *
     * @param deleteFlag the value for t_interface_permission.delete_flag
     *
     * @mbg.generated Tue Jul 30 13:30:34 CST 2019
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}