package common.plugin.authority.dmo;

import java.util.Date;

public class RolePermissionInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role_permission_info.id
	 * @mbg.generated  Tue Jul 30 13:28:24 CST 2019
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role_permission_info.role_code
	 * @mbg.generated  Tue Jul 30 13:28:24 CST 2019
	 */
	private String roleCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role_permission_info.permission_id
	 * @mbg.generated  Tue Jul 30 13:28:24 CST 2019
	 */
	private String permissionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role_permission_info.delete_flag
	 * @mbg.generated  Tue Jul 30 13:28:24 CST 2019
	 */
	private String deleteFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role_permission_info.create_uer_code
	 * @mbg.generated  Tue Jul 30 13:28:24 CST 2019
	 */
	private String createUerCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role_permission_info.update_user_code
	 * @mbg.generated  Tue Jul 30 13:28:24 CST 2019
	 */
	private String updateUserCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role_permission_info.create_time
	 * @mbg.generated  Tue Jul 30 13:28:24 CST 2019
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role_permission_info.update_time
	 * @mbg.generated  Tue Jul 30 13:28:24 CST 2019
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role_permission_info.client_id
	 * @mbg.generated  Tue Jul 30 13:28:24 CST 2019
	 */
	private String clientId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role_permission_info.id
	 * @return  the value of t_role_permission_info.id
	 * @mbg.generated  Tue Jul 30 13:28:24 CST 2019
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role_permission_info.id
	 * @param id  the value for t_role_permission_info.id
	 * @mbg.generated  Tue Jul 30 13:28:24 CST 2019
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role_permission_info.role_code
	 * @return  the value of t_role_permission_info.role_code
	 * @mbg.generated  Tue Jul 30 13:28:24 CST 2019
	 */
	public String getRoleCode() {
		return roleCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role_permission_info.role_code
	 * @param roleCode  the value for t_role_permission_info.role_code
	 * @mbg.generated  Tue Jul 30 13:28:24 CST 2019
	 */
	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role_permission_info.permission_id
	 * @return  the value of t_role_permission_info.permission_id
	 * @mbg.generated  Tue Jul 30 13:28:24 CST 2019
	 */
	public String getPermissionId() {
		return permissionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role_permission_info.permission_id
	 * @param permissionId  the value for t_role_permission_info.permission_id
	 * @mbg.generated  Tue Jul 30 13:28:24 CST 2019
	 */
	public void setPermissionId(String permissionId) {
		this.permissionId = permissionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role_permission_info.delete_flag
	 * @return  the value of t_role_permission_info.delete_flag
	 * @mbg.generated  Tue Jul 30 13:28:24 CST 2019
	 */
	public String getDeleteFlag() {
		return deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role_permission_info.delete_flag
	 * @param deleteFlag  the value for t_role_permission_info.delete_flag
	 * @mbg.generated  Tue Jul 30 13:28:24 CST 2019
	 */
	public void setDeleteFlag(String deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role_permission_info.create_uer_code
	 * @return  the value of t_role_permission_info.create_uer_code
	 * @mbg.generated  Tue Jul 30 13:28:24 CST 2019
	 */
	public String getCreateUerCode() {
		return createUerCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role_permission_info.create_uer_code
	 * @param createUerCode  the value for t_role_permission_info.create_uer_code
	 * @mbg.generated  Tue Jul 30 13:28:24 CST 2019
	 */
	public void setCreateUerCode(String createUerCode) {
		this.createUerCode = createUerCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role_permission_info.update_user_code
	 * @return  the value of t_role_permission_info.update_user_code
	 * @mbg.generated  Tue Jul 30 13:28:24 CST 2019
	 */
	public String getUpdateUserCode() {
		return updateUserCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role_permission_info.update_user_code
	 * @param updateUserCode  the value for t_role_permission_info.update_user_code
	 * @mbg.generated  Tue Jul 30 13:28:24 CST 2019
	 */
	public void setUpdateUserCode(String updateUserCode) {
		this.updateUserCode = updateUserCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role_permission_info.create_time
	 * @return  the value of t_role_permission_info.create_time
	 * @mbg.generated  Tue Jul 30 13:28:24 CST 2019
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role_permission_info.create_time
	 * @param createTime  the value for t_role_permission_info.create_time
	 * @mbg.generated  Tue Jul 30 13:28:24 CST 2019
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role_permission_info.update_time
	 * @return  the value of t_role_permission_info.update_time
	 * @mbg.generated  Tue Jul 30 13:28:24 CST 2019
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role_permission_info.update_time
	 * @param updateTime  the value for t_role_permission_info.update_time
	 * @mbg.generated  Tue Jul 30 13:28:24 CST 2019
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role_permission_info.client_id
	 * @return  the value of t_role_permission_info.client_id
	 * @mbg.generated  Tue Jul 30 13:28:24 CST 2019
	 */
	public String getClientId() {
		return clientId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role_permission_info.client_id
	 * @param clientId  the value for t_role_permission_info.client_id
	 * @mbg.generated  Tue Jul 30 13:28:24 CST 2019
	 */
	public void setClientId(String clientId) {
		this.clientId = clientId;
	}
}