package common.plugin.authority.dmo;

import java.util.Date;

public class RoleBasicInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_basic_info.id
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_basic_info.role_code
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    private String roleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_basic_info.role_name
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_basic_info.role_desc
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    private String roleDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_basic_info.delete_flag
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    private Integer deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_basic_info.role_tag
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    private String roleTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_basic_info.create_time
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_basic_info.update_time
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_basic_info.create_user_code
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    private String createUserCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_basic_info.update_user_code
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    private String updateUserCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_basic_info.id
     *
     * @return the value of t_role_basic_info.id
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_basic_info.id
     *
     * @param id the value for t_role_basic_info.id
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_basic_info.role_code
     *
     * @return the value of t_role_basic_info.role_code
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_basic_info.role_code
     *
     * @param roleCode the value for t_role_basic_info.role_code
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_basic_info.role_name
     *
     * @return the value of t_role_basic_info.role_name
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_basic_info.role_name
     *
     * @param roleName the value for t_role_basic_info.role_name
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_basic_info.role_desc
     *
     * @return the value of t_role_basic_info.role_desc
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_basic_info.role_desc
     *
     * @param roleDesc the value for t_role_basic_info.role_desc
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_basic_info.delete_flag
     *
     * @return the value of t_role_basic_info.delete_flag
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_basic_info.delete_flag
     *
     * @param deleteFlag the value for t_role_basic_info.delete_flag
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_basic_info.role_tag
     *
     * @return the value of t_role_basic_info.role_tag
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    public String getRoleTag() {
        return roleTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_basic_info.role_tag
     *
     * @param roleTag the value for t_role_basic_info.role_tag
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    public void setRoleTag(String roleTag) {
        this.roleTag = roleTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_basic_info.create_time
     *
     * @return the value of t_role_basic_info.create_time
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_basic_info.create_time
     *
     * @param createTime the value for t_role_basic_info.create_time
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_basic_info.update_time
     *
     * @return the value of t_role_basic_info.update_time
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_basic_info.update_time
     *
     * @param updateTime the value for t_role_basic_info.update_time
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_basic_info.create_user_code
     *
     * @return the value of t_role_basic_info.create_user_code
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    public String getCreateUserCode() {
        return createUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_basic_info.create_user_code
     *
     * @param createUserCode the value for t_role_basic_info.create_user_code
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    public void setCreateUserCode(String createUserCode) {
        this.createUserCode = createUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_basic_info.update_user_code
     *
     * @return the value of t_role_basic_info.update_user_code
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    public String getUpdateUserCode() {
        return updateUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_basic_info.update_user_code
     *
     * @param updateUserCode the value for t_role_basic_info.update_user_code
     *
     * @mbg.generated Tue Jul 30 13:28:24 CST 2019
     */
    public void setUpdateUserCode(String updateUserCode) {
        this.updateUserCode = updateUserCode;
    }
}