package common.plugin.authority.dmo;

import java.util.Date;

public class UserRoleInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role_info.id
     *
     * @mbg.generated Tue Jul 30 13:26:21 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role_info.user_code
     *
     * @mbg.generated Tue Jul 30 13:26:21 CST 2019
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role_info.role_code
     *
     * @mbg.generated Tue Jul 30 13:26:21 CST 2019
     */
    private String roleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role_info.delete_flag
     *
     * @mbg.generated Tue Jul 30 13:26:21 CST 2019
     */
    private Integer deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role_info.update_user_code
     *
     * @mbg.generated Tue Jul 30 13:26:21 CST 2019
     */
    private String updateUserCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role_info.create_user_code
     *
     * @mbg.generated Tue Jul 30 13:26:21 CST 2019
     */
    private String createUserCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role_info.create_time
     *
     * @mbg.generated Tue Jul 30 13:26:21 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role_info.update_time
     *
     * @mbg.generated Tue Jul 30 13:26:21 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role_info.id
     *
     * @return the value of t_user_role_info.id
     *
     * @mbg.generated Tue Jul 30 13:26:21 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role_info.id
     *
     * @param id the value for t_user_role_info.id
     *
     * @mbg.generated Tue Jul 30 13:26:21 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role_info.user_code
     *
     * @return the value of t_user_role_info.user_code
     *
     * @mbg.generated Tue Jul 30 13:26:21 CST 2019
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role_info.user_code
     *
     * @param userCode the value for t_user_role_info.user_code
     *
     * @mbg.generated Tue Jul 30 13:26:21 CST 2019
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role_info.role_code
     *
     * @return the value of t_user_role_info.role_code
     *
     * @mbg.generated Tue Jul 30 13:26:21 CST 2019
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role_info.role_code
     *
     * @param roleCode the value for t_user_role_info.role_code
     *
     * @mbg.generated Tue Jul 30 13:26:21 CST 2019
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role_info.delete_flag
     *
     * @return the value of t_user_role_info.delete_flag
     *
     * @mbg.generated Tue Jul 30 13:26:21 CST 2019
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role_info.delete_flag
     *
     * @param deleteFlag the value for t_user_role_info.delete_flag
     *
     * @mbg.generated Tue Jul 30 13:26:21 CST 2019
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role_info.update_user_code
     *
     * @return the value of t_user_role_info.update_user_code
     *
     * @mbg.generated Tue Jul 30 13:26:21 CST 2019
     */
    public String getUpdateUserCode() {
        return updateUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role_info.update_user_code
     *
     * @param updateUserCode the value for t_user_role_info.update_user_code
     *
     * @mbg.generated Tue Jul 30 13:26:21 CST 2019
     */
    public void setUpdateUserCode(String updateUserCode) {
        this.updateUserCode = updateUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role_info.create_user_code
     *
     * @return the value of t_user_role_info.create_user_code
     *
     * @mbg.generated Tue Jul 30 13:26:21 CST 2019
     */
    public String getCreateUserCode() {
        return createUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role_info.create_user_code
     *
     * @param createUserCode the value for t_user_role_info.create_user_code
     *
     * @mbg.generated Tue Jul 30 13:26:21 CST 2019
     */
    public void setCreateUserCode(String createUserCode) {
        this.createUserCode = createUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role_info.create_time
     *
     * @return the value of t_user_role_info.create_time
     *
     * @mbg.generated Tue Jul 30 13:26:21 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role_info.create_time
     *
     * @param createTime the value for t_user_role_info.create_time
     *
     * @mbg.generated Tue Jul 30 13:26:21 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role_info.update_time
     *
     * @return the value of t_user_role_info.update_time
     *
     * @mbg.generated Tue Jul 30 13:26:21 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role_info.update_time
     *
     * @param updateTime the value for t_user_role_info.update_time
     *
     * @mbg.generated Tue Jul 30 13:26:21 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}